name: half_gaussian_splatting
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cuda-cudart-dev=11.6.55
  - cuda-nvcc=11.6.55
  - cudatoolkit=11.6
  - gcc_linux-64=10
  - gxx_linux-64=10
  - libxcrypt
  - mkl<2024
  - ninja
  - pillow=9.2.0
  - libtiff=4.4.0
  - plyfile
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - lpips==0.1.4
    - scipy==1.7.3
